export const MEBIBYTE = 1024 * 1024;
export const GIBIBYTE = 1024 * MEBIBYTE;

const users = [
  { id: "user-owner", displayName: "码头", avatar: "码", color: "teal", presence: "online" },
  { id: "user-lin", displayName: "林小满", avatar: "林", color: "teal", presence: "online" },
  { id: "user-zhou", displayName: "周远", avatar: "周", color: "blue", presence: "online" },
  { id: "user-su", displayName: "苏禾", avatar: "苏", color: "amber", presence: "away" },
  { id: "user-chen", displayName: "陈墨", avatar: "陈", color: "slate", presence: "offline" },
];

const files = [
  {
    id: "file-shared-design",
    scope: "shared",
    name: "设计稿最终版.zip",
    alias: null,
    mimeLabel: "ZIP 压缩文件",
    kind: "archive",
    sizeBytes: 128 * MEBIBYTE,
    uploaderId: "user-owner",
    recipientIds: [],
    receiverStates: {},
    status: "available",
    createdAt: "2026-07-31T14:18:00+08:00",
  },
  {
    id: "file-direct-budget",
    scope: "direct",
    name: "项目预算明细.xlsx",
    alias: "7K2M-A9Q4",
    mimeLabel: "XLSX 表格",
    kind: "sheet",
    sizeBytes: 8.4 * MEBIBYTE,
    uploaderId: "user-owner",
    recipientIds: ["user-lin", "user-zhou"],
    receiverStates: { "user-lin": "accepted", "user-zhou": "accepted" },
    status: "available",
    createdAt: "2026-07-31T13:46:00+08:00",
  },
  {
    id: "file-direct-audit",
    scope: "direct",
    name: "候选人资料.pdf",
    alias: "2PX8-L6RD",
    mimeLabel: "PDF 文档",
    kind: "document",
    sizeBytes: 56 * MEBIBYTE,
    uploaderId: "user-zhou",
    recipientIds: ["user-lin"],
    receiverStates: { "user-lin": "downloaded" },
    status: "available",
    createdAt: "2026-07-31T12:30:00+08:00",
  },
  {
    id: "file-shared-video",
    scope: "shared",
    name: "产品演示视频.mp4",
    alias: null,
    mimeLabel: "MP4 视频",
    kind: "video",
    sizeBytes: 240 * MEBIBYTE,
    uploaderId: "user-su",
    recipientIds: [],
    receiverStates: {},
    status: "uploading",
    uploadProgress: 46,
    createdAt: "2026-07-31T14:24:00+08:00",
  },
  {
    id: "file-shared-guide",
    scope: "shared",
    name: "使用说明.pdf",
    alias: null,
    mimeLabel: "PDF 文档",
    kind: "document",
    sizeBytes: 42 * MEBIBYTE,
    uploaderId: "user-lin",
    recipientIds: [],
    receiverStates: {},
    status: "available",
    createdAt: "2026-07-30T17:20:00+08:00",
  },
  {
    id: "file-direct-owner-copy",
    scope: "direct",
    name: "设备清单.csv",
    alias: "9NQM-C4T7",
    mimeLabel: "CSV 表格",
    kind: "sheet",
    sizeBytes: 64 * MEBIBYTE,
    uploaderId: "user-lin",
    recipientIds: ["user-owner"],
    receiverStates: { "user-owner": "pending" },
    status: "available",
    createdAt: "2026-07-30T16:15:00+08:00",
  },
  {
    id: "file-recycled-shared",
    scope: "shared",
    name: "旧版素材包.zip",
    alias: null,
    mimeLabel: "ZIP 压缩文件",
    kind: "archive",
    sizeBytes: 120 * MEBIBYTE,
    uploaderId: "user-owner",
    recipientIds: [],
    receiverStates: {},
    status: "recycled",
    removedById: "user-owner",
    removalKind: "self",
    recycledAt: "2026-07-31T11:40:00+08:00",
    createdAt: "2026-07-29T09:10:00+08:00",
  },
  {
    id: "file-recycled-direct",
    scope: "direct",
    name: "内部报价单.docx",
    alias: "6WRT-H3K8",
    mimeLabel: "DOCX 文档",
    kind: "document",
    sizeBytes: 72 * MEBIBYTE,
    uploaderId: "user-zhou",
    recipientIds: ["user-lin"],
    receiverStates: { "user-lin": "accepted" },
    status: "recycled",
    removedById: "user-owner",
    removalKind: "owner_forced",
    recycledAt: "2026-07-31T10:22:00+08:00",
    createdAt: "2026-07-30T15:20:00+08:00",
  },
];

const events = [
  { id: "event-1", type: "upload_completed", fileId: "file-shared-design", actorId: "user-owner", occurredAt: "2026-07-31T14:18:00+08:00" },
  { id: "event-2", type: "download_completed", fileId: "file-shared-design", actorId: "user-lin", occurredAt: "2026-07-31T14:22:00+08:00" },
  { id: "event-3", type: "direct_sent", fileId: "file-direct-budget", actorId: "user-owner", occurredAt: "2026-07-31T13:46:00+08:00" },
  { id: "event-4", type: "download_completed", fileId: "file-direct-audit", actorId: "user-lin", occurredAt: "2026-07-31T13:05:00+08:00" },
  { id: "event-5", type: "upload_progress", fileId: "file-shared-video", actorId: "user-su", occurredAt: "2026-07-31T14:24:00+08:00", progress: 46 },
  { id: "event-6", type: "recycled", fileId: "file-recycled-shared", actorId: "user-owner", occurredAt: "2026-07-31T11:40:00+08:00" },
];

const messages = [
  { id: "message-1", fromId: "user-lin", toId: "user-owner", type: "text", text: "文件已经收到，谢谢。", status: "read", createdAt: "2026-07-31T14:20:00+08:00" },
  { id: "message-2", fromId: "user-owner", toId: "user-lin", type: "text", text: "共享文件引用也会出现在这里。", status: "read", createdAt: "2026-07-31T14:21:00+08:00" },
];

const clone = (value) => JSON.parse(JSON.stringify(value));

export function createMockState() {
  return {
    room: {
      id: "room-01J6YROOM",
      code: "1234",
      title: "设计协作间",
      ownerId: "user-owner",
      status: "active",
      memberCount: 8,
      expiresAt: "2026-08-01T00:48:36+08:00",
      capacityBytes: 2 * GIBIBYTE,
    },
    users: clone(users),
    files: clone(files),
    events: clone(events),
    messages: clone(messages),
    tasks: [],
    readCursors: { "user-owner:user-lin": "message-2" },
    recycleConfig: {
      countTowardRoomCapacity: false,
      freeBytes: 128 * MEBIBYTE,
    },
    ui: {
      currentUserId: "user-owner",
      language: "zh-CN",
      scenario: "workspace",
      activeFileTab: "files",
      fileSearch: "",
      fileScopeFilter: "all",
      fileSort: "newest",
      selectedChatUserId: "user-lin",
      selectedFileIds: [],
      selectedRecipientIds: [],
      composer: null,
      modal: null,
      drawer: null,
    },
  };
}
