[app]
name = "filedock"
env = "dev"
data_dir = "data"

[http]
addr = ":8195"
cert_file = ""
key_file = ""

[log]
enable = true
level = "info"
output = "stdout"
file = "data/logs/filedock.log"
caller = true

[sqlite]
path = "data/filedock.db"
