// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/leafney/filedock/core"
)

// Injectors from wire.go:

func InitializeApp(configPath string, build core.BuildInfo) (*core.App, error) {
	config, err := provideConfig(configPath)
	if err != nil {
		return nil, err
	}
	zLogSvc := provideLogger(config)
	gormDBSvc, err := provideSQLiteDB(config, zLogSvc)
	if err != nil {
		return nil, err
	}
	streamHub := provideStreamHub()
	fileStorage, err := provideFileStorage(config)
	if err != nil {
		return nil, err
	}
	fileSvc, err := provideFileSvc(gormDBSvc, streamHub, fileStorage)
	if err != nil {
		return nil, err
	}
	lifecycleSvc, err := provideLifecycleSvc(gormDBSvc, streamHub, fileStorage, fileSvc)
	if err != nil {
		return nil, err
	}
	catalog, err := provideI18nCatalog(zLogSvc)
	if err != nil {
		return nil, err
	}
	versionSvc := provideVersionSvc(build)
	versionBiz, err := provideVersionBiz(versionSvc)
	if err != nil {
		return nil, err
	}
	versionAPI, err := provideVersionAPI(versionBiz)
	if err != nil {
		return nil, err
	}
	nicknameSvc, err := provideNicknameSvc(gormDBSvc)
	if err != nil {
		return nil, err
	}
	sessionSvc, err := provideSessionSvc(config, gormDBSvc, nicknameSvc, streamHub)
	if err != nil {
		return nil, err
	}
	sessionBiz, err := provideSessionBiz(sessionSvc, nicknameSvc)
	if err != nil {
		return nil, err
	}
	sessionAPI, err := provideSessionAPI(sessionBiz, config)
	if err != nil {
		return nil, err
	}
	presenceSvc, err := providePresenceSvc(gormDBSvc, streamHub)
	if err != nil {
		return nil, err
	}
	roomSvc, err := provideRoomSvc(gormDBSvc, streamHub, presenceSvc, fileSvc)
	if err != nil {
		return nil, err
	}
	roomBiz, err := provideRoomBiz(roomSvc)
	if err != nil {
		return nil, err
	}
	roomAPI, err := provideRoomAPI(roomBiz)
	if err != nil {
		return nil, err
	}
	fileBiz, err := provideFileBiz(fileSvc)
	if err != nil {
		return nil, err
	}
	fileAPI, err := provideFileAPI(fileBiz)
	if err != nil {
		return nil, err
	}
	streamAPI, err := provideStreamAPI(streamHub, presenceSvc)
	if err != nil {
		return nil, err
	}
	rateLimiter := provideRateLimiter()
	server, err := provideServer(config, zLogSvc, catalog, versionAPI, sessionAPI, sessionSvc, roomAPI, fileAPI, streamAPI, rateLimiter)
	if err != nil {
		return nil, err
	}
	app, err := provideApp(config, zLogSvc, gormDBSvc, lifecycleSvc, server)
	if err != nil {
		return nil, err
	}
	return app, nil
}
