// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/leafney/filedock/core"
)

// Injectors from wire.go:

func InitializeApp(configPath string, build core.BuildInfo) (*core.App, error) {
	config, err := provideConfig(configPath)
	if err != nil {
		return nil, err
	}
	zLogSvc := provideLogger(config)
	gormDBSvc, err := provideSQLiteDB(config, zLogSvc)
	if err != nil {
		return nil, err
	}
	catalog, err := provideI18nCatalog(zLogSvc)
	if err != nil {
		return nil, err
	}
	versionSvc := provideVersionSvc(build)
	versionBiz, err := provideVersionBiz(versionSvc)
	if err != nil {
		return nil, err
	}
	versionAPI, err := provideVersionAPI(versionBiz)
	if err != nil {
		return nil, err
	}
	nicknameSvc, err := provideNicknameSvc(gormDBSvc)
	if err != nil {
		return nil, err
	}
	sessionSvc, err := provideSessionSvc(config, gormDBSvc, nicknameSvc)
	if err != nil {
		return nil, err
	}
	sessionBiz, err := provideSessionBiz(sessionSvc, nicknameSvc)
	if err != nil {
		return nil, err
	}
	sessionAPI, err := provideSessionAPI(sessionBiz, config)
	if err != nil {
		return nil, err
	}
	roomSvc, err := provideRoomSvc(gormDBSvc)
	if err != nil {
		return nil, err
	}
	roomBiz, err := provideRoomBiz(roomSvc)
	if err != nil {
		return nil, err
	}
	roomAPI, err := provideRoomAPI(roomBiz)
	if err != nil {
		return nil, err
	}
	server, err := provideServer(config, zLogSvc, catalog, versionAPI, sessionAPI, sessionSvc, roomAPI)
	if err != nil {
		return nil, err
	}
	app, err := provideApp(config, zLogSvc, gormDBSvc, server)
	if err != nil {
		return nil, err
	}
	return app, nil
}
